name: garbage_app
description: SafaiPay â€“ Clean Actions. Real Rewards.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10

  # State Management
  provider: ^6.1.1

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Camera & Images
  image_picker: ^1.0.7
  camera: ^0.10.5+9

  # Payment
  razorpay_flutter: ^1.3.6

  # UI / Utils
  intl: ^0.19.0
  lottie: ^3.3.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  shimmer: ^3.0.0
  confetti: ^0.7.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#F4F7F5"
  image: assets/images/splash_icon.png
  android: true
  ios: true
  color_dark: "#F4F7F5"
